config/routes.rb
Rails.application.routes.draw do
  resources :artists do
    resources :songs, shallow: true
  end

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :image_path, presence: true

  has_many :songs
end

app/models/song.rb
class Song < ActiveRecord::Base
  validates :title, presence: true
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to @artist
    else
      render :new
    end
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])
    @artist.update(artist_params)
    redirect_to artist_path(@artist)
  end

  def destroy
    @artist = Artist.find(params[:id])
    Artist.delete(@artist)
    redirect_to artists_path
  end

  private

  def artist_params
    params.require(:artist).permit(:name, :image_path)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    @artists = Artist.all
  end

  def show
    @song = Song.find(params[:id])
  end
  
  def new
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.new
  end

  def create
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.new(song_params)

    if @song.save
      redirect_to song_path(@song)
    else
      render :new
    end
  end

  def edit
    @song = Song.find(params[:id])
  end

  def update
    @song = Song.update(params[:id], song_params)

    redirect_to song_path(@song)
  end

  private

  def song_params
    params.require(:song).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% @artist.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :image_path %>
  <%= f.text_field :image_path %>

  <%= f.submit %>
<% end %>

app/views/artists/edit.html.erb
<%= render partial: "form" %>

app/views/artists/index.html.erb
<h1>All Artists</h1>
<%= link_to "New Artist", new_artist_path %>
<%= @artists.each do |artist| %>
  <%= link_to artist.name, artist_path(artist) %>
<% end %>

app/views/artists/new.html.erb
<%= render partial: "form" %>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>
<%= image_tag @artist.image_path %>
<%= link_to "Edit", edit_artist_path(@artist) %>
<%= link_to "Delete", artist_path(@artist), method: :delete %>
<%= link_to "New Song", new_artist_song_path(@artist) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MixMaster</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/songs/_form.html.erb
<%= form_for([@artist, @song]) do |f| %>

  <% if @song.errors.any? %>
    <ul>
      <% @song.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  <% end %>
    
  <%= f.label :title%>
  <%= f.text_field :title %>

  <%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<h1>Edit Song</h1>
<%= render partial: "form" %>

app/views/songs/index.html.erb
<h1>All Songs for <%= @artist.name %>
<ul>
  <%= @songs.each do |song| %>
    <li><%= song %></li>
  <% end %>
</ul>
    

app/views/songs/new.html.erb
<h1>New Song</h1>
<p>Create a new song for <%= @artist.name %></p>
<%= render partial: "form" %>

app/views/songs/show.html.erb
<h1><%= @song.title %></h1>
<%= link_to @song.artist.name, artist_path(@song.artist) %>
<%= link_to "Edit", edit_song_path(@song) %>